services:
  postgres:
    image: postgres:15
    restart: always
    container_name: release_manager_db
    environment:
      POSTGRES_DB: release_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'  # исправлено здесь
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: